spring:
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
  # 国际化
  messages:
    basename: i18n/messages
  # 编码
  http:
    encoding:
      force: true
  profiles:
    active:
    - feign
# 关闭默认空白标签
server:
  error:
    whitelabel:
      enabled: false
# 用于显示的信息
info:
  author: wangtao
  email: wangt@disanbo.com
# 监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
